# Generated by Django 3.1.14 on 2022-05-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='title',
            field=models.TextField(max_length=200, verbose_name='Pokemon'),
        ),
    ]
