# Generated by Django 3.1.14 on 2022-05-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0002_auto_20220528_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1024, verbose_name='Описание'),
        ),
    ]
