# Generated by Django 3.1.14 on 2022-05-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0003_pokemon_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='title',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='title_en',
            field=models.TextField(blank=True, default='', max_length=200, verbose_name='Имя на английском'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='title_jp',
            field=models.TextField(blank=True, default='', max_length=200, verbose_name='Имя на японском'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='title_ru',
            field=models.TextField(blank=True, default='', max_length=200, verbose_name='Имя на русском'),
        ),
    ]
