# Generated by Django 3.1.14 on 2022-05-29 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0005_auto_20220529_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='next_evolution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pokemon_next_evol', to='pokemon_entities.pokemon', verbose_name='Следующий этап эволюции'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='previous_evolution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pokemon_prev_evol', to='pokemon_entities.pokemon', verbose_name='Предыдущий этап эволюции'),
        ),
    ]
