# Generated by Django 3.1.14 on 2022-06-03 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0009_auto_20220603_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='previous_evolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prev_evol_pokemon', to='pokemon_entities.pokemon', verbose_name='Предыдущий этап эволюции'),
        ),
    ]
