# Generated by Django 3.1.14 on 2022-06-04 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0011_auto_20220604_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='previous_evolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='next_evolutions', to='pokemon_entities.pokemon', verbose_name='Предыдущий этап эволюции'),
        ),
    ]
